# Generated by Django 4.2.16 on 2024-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_alter_character_name_alter_weapon_damage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
