# Generated by Django 4.2.16 on 2024-12-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0011_spell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_4',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_5',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_6',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_7',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_8',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spell_slots_total_level_9',
        ),
    ]
