# Generated by Django 4.2.16 on 2024-12-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_remove_character_spell_slots_total_level_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='attack_bonus_save_dc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
