# Generated by Django 4.2.16 on 2024-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0014_alter_spell_casting_time_alter_spell_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attack_bonus_save_dc_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='attack_bonus_save_dc_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='damage_type_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='damage_type_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_notes_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_notes_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
