# Generated by Django 4.2.16 on 2024-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_character_attack_bonus_save_dc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spell_casting_time_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_casting_time_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_casting_time_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_casting_time_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_casting_time_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_concentration_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_concentration_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_concentration_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_concentration_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_concentration_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_level_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_level_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_level_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_level_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_level_5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_material_required_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_material_required_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_material_required_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_material_required_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_material_required_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_name_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_name_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_name_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_name_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_notes_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_notes_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_notes_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_notes_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_notes_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_range_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_range_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_range_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_range_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_range_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_ritual_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_ritual_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_ritual_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_ritual_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_ritual_5',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
    ]
